theme: jekyll-theme-architect

# 叶正梗

# 职称：副研究员
# 导师类别：硕士导师
# 邮箱：yezhenggeng@zzu.edu.cn
# 研究方向：制造系统建模、分析与优化；可靠性建模；机器学习；工业大数据分析；智能制造. 
# 教育经历：
2018.03-2021.12，西北工业大学，机电学院工业工程系，管理学博士；<br>
2019.11-2021.10，宾夕法尼亚州立大学（帕克校区），工业与制造工程系，联合培养博士（国家留学基金委资助）；<br>
2012.09-2015.07，吉林大学，机械科学与工程学院工业工程系，工学硕士；<br>
2008.09-2012.07，河南科技大学，机电学院工业工程系，工学学士。<br>
# 企业经历：
2015.08-2018.02，中国船舶重工集团公司第713研究所，生产部；<br>
2013.10-2014.08，徐工随车起重机有限公司，结构件分厂。<br>

# 个人简介
叶正梗，男，河南商丘人。2021年毕业于西北工业大学，管理学博士，宾夕法尼亚州立大学联合培养博士。目前，累积发表SCI/EI索引学术论文10余篇（最新论文进展请参考Research Gate个人主页）。国家自然科学基金委函评专家, IISE Member (Institute of Industrial and Systems Engineers), IEEE Reliability Society Member, IEEE Industrial Electronics Society Member, IEEE Computational Intelligence Society Member。
带队参加“挑战杯”大学生课外学术科技作品竞赛获得校级一等奖。<br>
个人主页（Research Gate）： https://www.researchgate.net/profile/Zhenggeng-Ye

# 主讲课程
[1]	本科生课程：《应用统计学》、《工业设计基础》。


# 承担/参与科研项目
[1]	基于数据融合的多级制造系统质量与可靠性耦合建模与优化， 国家自然科学基金（青年项目），2023.01-2025.12，主持；<br>
[2]	考虑级联失效的复杂制造系统任务可靠性分析与优化，西北工业大学博士论文创新基金，2020.01-2021.12，主持；<br>
[3]	基于弹性指标的可重构系统性能分析及优化，国家自然科学基金（面上项目），2019.01-2022.12，参与；<br>
[4]	系统可靠性建模与分析的理论与方法研究， 国家自然科学基金（重点项目），2017.01-2021.12，参与；<br>
[5]	人员胜任力视角下多模式资源约束型多目标研发项目组合调度优化，陕西省自然科学基础研究计划（面上项目），2021.01 -2021.12，参与。<br>

# 发表论文情况
期刊论文：
[1] Zhenggeng Ye, Zhiqiang Cai, Hui Yang, Shubin Si, Fuli Zhou. Joint optimization of maintenance and quality inspection for manufacturing networks based on deep reinforcement learning. Reliability Engineering & System Safety. 2023, 236, 109290。<br>
[2] Zhenggeng Ye, Shubin Si, Hui Yang, Zhiqiang Cai, Fuli Zhou. Machine and Feedstock Interdependence Modeling for Manufacturing Networks Performance Analysis [J]. IEEE Transactions on Industrial Informatics. 2022, 18(8): 5067-5076。<br>
[3] Zhenggeng Ye, Zhiqiang Cai, Shubin Si, Fuli Zhou. Operational Reliability and Quality Loss of Diversely Configurated Manufacturing Cells with Heterogeneous Feedstocks [J]. Proceedings of the Institution of Mechanical Engineers Part O: Journal of Risk and Reliability. 2022;236(6):955-967.<br>
[4] Zhenggeng Ye, Hui Yang, Zhiqiang Cai, Shubin Si, Fuli Zhou. Performance evaluation of serial-parallel manufacturing systems based on the impact of heterogeneous feedstocks on machine degradation[J]. Reliability Engineering & System Safety, 2021, 207: 107319.<br> 
[5] Zhenggeng Ye, Zhiqiang Cai, Shubin Si, Shuai Zhang, Hui Yang. Competing failure modeling for performance analysis of automated manufacturing systems with serial structures and imperfect quality inspection[J]. IEEE Transactions on Industrial Informatics, 2020, 16(10): 6476-6486. <br>
[6] Zhenggeng Ye, Zhiqiang Cai, Fuli Zhou, Jiangbin Zhao, Pan Zhang. Reliability analysis for series manufacturing system with imperfect inspection considering the interaction between quality and degradation[J]. Reliability Engineering & System Safety, 2019, 189: 345-356. <br>
[7] Yongjun Du, Zhenggeng Ye, Pan Zhang, Yaqi Guo, Zhiqiang Cai. Evaluating network importance measures based on the construction spectrum [J]. Advances in Mechanical Engineering, 2019, 11(3): 1687814019830836. <br>
[8] 叶正梗, 蔡志强, 周福礼. 基于多层次复杂度的工时定额综合研究[J]. 计算机集成制造系统, 2019, 25(3): 556-565.<br>
[9] 周福礼, 叶正梗. 基于 SIR-HCA 模型的自主品牌汽车企业负面口碑扩散研究[J]. 计算机集成制造系统, 2021, 27 (12), 3669-3681.<br>
[10] 陈俊杰, 同淑荣, 叶正梗, 张静文, 王曜, 聂亚菲. 资源受限多项目调度问题的两阶段算法[J]. 控制与决策, 2020, 35(8): 2013-2020. <br>
[11] 周福礼, 王旭, 叶正梗, 林云, 何彦东. 基于系统动力学仿真的国产汽车质量经济性研究[J]. 计算机集成制造系统, 2019, 25(2): 508-519. <br>
[12] 孔繁森, 叶正梗. 生产作业可操作性评价理论方法框架模型研究[J]. 机械工程学报, 2017, 4: 028.<br>

# 会议论文： 
[1] Zhenggeng Ye, Zhiqiang Cai, Fuli Zhou, Pan Zhang. Degradation Analysis of Machine Processing Accuracy for Manufacturing Systems with Effect of Unqualified Products [C]. 2020 Annual Reliability and Maintainability Symposium (RAMS). IEEE, 2020: 1-6. <br>
[2] Zhenggeng Ye, Zhiqiang Cai, Hui Yang. Reliability Analysis of Manufacturing Machine with Degradation and Low-quality Feedstocks [C]. 2020 Asia-Pacific International Symposium on Advanced Reliability and Maintenance Modeling (APARM). IEEE, 2020: 1-5.<br>
[3] Zhenggeng Ye, Jiachao Cui, Fuli Zhou. Man-hour Estimation Model based on Standard Operation Unit for Flexible Manufacturing System [C]. 13th Global Congress on Manufacturing and Management (GCMM). EDP Sciences, 2017, 100: 02017. <br>

# 发明专利：
[1] 蔡志强; 韩思杰; 王宇航; 司书宾; 张帅; 叶正梗. 基于贝叶斯分类器链的涡轴发动机多目标性能预测方法；2021-02-02, 中国, CN202110140394.0.（授权）

# 学术报告：
(1) 2022年中国统筹法优选法及经济数学学会工业工程分会学术交流暨学会年会, 2022.11，“工况监测驱动下的设备动态可靠性评价方法”。<br>
(2) IISE Annual Conference & Expo, 2021.05， “Machine Dependence Caused by Low-quality Feedstocks in Manufacturing Networks” .<br>
(3) The 9th Asia-Pacific International Symposium on Advanced Reliability and Maintenance Modeling (APARM)， 2020.08， “ Reliability Analysis of Manufacturing Machine with Degradation and Low-quality Feedstocks”；<br>
(4) The 66th Annual Reliability & Maintainability Symposium (RAMS)，2020.01， “Degradation Analysis of Machine Processing Accuracy for Manufacturing Systems with Effect of Unqualified Products”；<br>
(5) The 4rd Sino-US Research Conference on Quality, Analytics and Innovations，2019.05，“Competing Failure Modeling for Performance Analysis of Manufacturing Systems”；<br>
(6) 清华大学主办“ 2018 年全国工业工程博士生学术论坛-暨优秀青年学者学术沙龙”，2018，“ 基于多层次复杂度的工时定额综合研究”。<br>


# 获奖情况
[1]	2021年度河南省高校哲学社会科学优秀研究成果三等奖（第二完成人）；<br>
[2]	2017 年“中国国防船舶科技报告-二级”（第一完成人）。
